captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80
email:
  host: smtp.qq.com
  port: 465
  from: 1948710271@qq.com
  nickname: 发件人昵称
  secret: xxxxxxxx
  is_ssl: true
es:
  url: http://localhost:9200
  username: ""
  password: ""
  is_console_print: true
gaode:
  enable: false
  key: xxxxxxxxxxxxx
jwt:
  access_token_secret: xxxxxxxxxxxxxxxxx
  refresh_token_secret: xxxxxxxxxxxxxxx
  access_token_expiry_time: 2h
  refresh_token_expiry_time: 7d
  issuer: go_blog
mysql:
  host: localhost
  port: 3307
  config: charset=utf8mb4&parseTime=True&loc=Local
  db_name: my_blog
  username: root
  password: root
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
qiniu:
  zone: z0
  bucket: xxx
  img_path: http://xxx.com/
  access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secret_key: xxxxxxxxxxxxxxxxxxxx
  use_https: true
  use_cdn_domains: true
qq:
  enable: false
  app_id: "000"
  app_key: xxxxx
  redirect_uri: "http://localhost:8080/api/v1/auth/qq/callback"
redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
system:
  host: 0.0.0.0
  port: 8080
  env: release
  router_prefix: api
  use_multipoint: true
  sessions_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  oss_type: local
upload:
  size: 20
  path: uploads
website:
  logo: ""
  full_logo: ""
  title: 博客标题-xxx的个人博客
  slogan: 博客标题
  slogan_en: Blog Title
  description: 博客描述
  version: 1.0.0
  created_at: "2026-1-17"
  icp_filing: icp备案号
  public_security_filing: 公安备案号
  bilibili_url: https://space.bilibili.com/170519473?spm_id_from=333.337.0.0
  gitee_url: https://gitee.com/tapir-heron
  github_url: https://github.com/TapirHeron
  name: 貘鹭
  job: 全干开发
  address: 地址
  email: 1948710271@qq.com
  qq_image: ""
  wechat_image: ""
zap:
  level: info
  filename: log/go_blog.log
  max_size: 200
  max_backups: 30
  max_age: 5
  is_console_print: true
